const Map<String, String> enUSStrings = {
  'app_name': 'HRV Master',
  'login': 'Login',
  'register': 'Register',
  'email': 'Email',
  'password': 'Password',
  'forgot_password': 'Forgot Password',
  'logout': 'Logout',
  'home': 'Home',
  'history': 'History',
  'profile': 'Profile',
  'reminders': 'Reminders',
  'measurement': 'Measurement',
  'start_measurement': 'Start Measurement',
  'results': 'Results',
  'rmssd': 'RMSSD',
  'sdnn': 'SDNN',
  'pnn50': 'pNN50',
  'lf': 'LF',
  'hf': 'HF',
  'lf_hf_ratio': 'LF/HF',
  'sd1': 'SD1',
  'sd2': 'SD2',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'settings': 'Settings',
  'theme': 'Theme',
  'language': 'Language',
  'light_theme': 'Light Theme',
  'dark_theme': 'Dark Theme',
  'portuguese': 'Portuguese',
  'english': 'English',
  'no_data': 'No data',
  'sync_status': 'Sync Status',
  'offline': 'Offline',
  'syncing': 'Syncing...',
  'synced': 'Synced',
  'camera': 'Camera (PPG)',
  'bluetooth': 'Bluetooth',
  'select_method': 'Select Method',
  'duration': 'Duration',
  'position': 'Position',
  'sitting': 'Sitting',
  'lying': 'Lying',
  'standing': 'Standing',
  'add_reminder': 'Add Reminder',
  'time': 'Time',
  'days': 'Days',
  'active': 'Active',
  'inactive': 'Inactive',
  'name': 'Name',
  'confirm_password': 'Confirm Password',
  'passwords_do_not_match': 'Passwords do not match',
  'field_required': 'Required field',
  'invalid_email': 'Invalid email',
  'weak_password': 'Password too weak (minimum 6 characters)',
  'user_not_found': 'User not found',
  'wrong_password': 'Wrong password',
  'error': 'Error',
  'success': 'Success',
  'loading': 'Loading...',
  'weekly_summary': 'Weekly Summary',
  'last_measurements': 'Last Measurements',
  'no_measurements': 'No measurements found',
  'measurement_detail': 'Measurement Detail',
  'date': 'Date',
  'method': 'Method',
  'device': 'Device',
  'send_reset_email': 'Send reset email',
  'reset_email_sent': 'Reset email sent!',
  'no_reminders': 'No reminders configured',
  'view_all': 'View all',
  'place_finger_on_camera': 'Place your finger on the rear camera',
  'measuring_bluetooth': 'Measuring via Bluetooth...',
  'finish_measurement': 'Finish Measurement',
  'wait_for_rr_intervals': 'Wait for at least 10 RR intervals ({count}/10)',
  'camera_subtitle': 'PPG via rear camera',
  'bluetooth_subtitle': 'Polar, Garmin or other BLE device',
  'time_domain': 'Time Domain',
  'poincare_plot': 'Poincaré Plot',
  'frequency_domain': 'Frequency Domain',
  'hrv_metrics': 'HRV Metrics',
  'delete_title': 'Delete',
  'delete_confirmation': 'Delete this measurement?',
  'greeting': 'Hello, {name}',
  'day_mon': 'Mon',
  'day_tue': 'Tue',
  'day_wed': 'Wed',
  'day_thu': 'Thu',
  'day_fri': 'Fri',
  'day_sat': 'Sat',
  'day_sun': 'Sun',
  'calculating_hrv': 'Calculating HRV metrics...',
  'rr_count': 'RR intervals: {count}',
};
