const Map<String, String> ptBRStrings = {
  'app_name': 'HRV Master',
  'login': 'Entrar',
  'register': 'Cadastrar',
  'email': 'E-mail',
  'password': 'Senha',
  'forgot_password': 'Esqueci a senha',
  'logout': 'Sair',
  'home': 'Início',
  'history': 'Histórico',
  'profile': 'Perfil',
  'reminders': 'Lembretes',
  'measurement': 'Medição',
  'start_measurement': 'Iniciar Medição',
  'results': 'Resultados',
  'rmssd': 'RMSSD',
  'sdnn': 'SDNN',
  'pnn50': 'pNN50',
  'lf': 'LF',
  'hf': 'HF',
  'lf_hf_ratio': 'LF/HF',
  'sd1': 'SD1',
  'sd2': 'SD2',
  'save': 'Salvar',
  'cancel': 'Cancelar',
  'delete': 'Excluir',
  'settings': 'Configurações',
  'theme': 'Tema',
  'language': 'Idioma',
  'light_theme': 'Tema Claro',
  'dark_theme': 'Tema Escuro',
  'portuguese': 'Português',
  'english': 'Inglês',
  'no_data': 'Sem dados',
  'sync_status': 'Status de Sincronização',
  'offline': 'Sem conexão',
  'syncing': 'Sincronizando...',
  'synced': 'Sincronizado',
  'camera': 'Câmera (PPG)',
  'bluetooth': 'Bluetooth',
  'select_method': 'Selecionar Método',
  'duration': 'Duração',
  'position': 'Posição',
  'sitting': 'Sentado',
  'lying': 'Deitado',
  'standing': 'Em pé',
  'add_reminder': 'Adicionar Lembrete',
  'time': 'Horário',
  'days': 'Dias',
  'active': 'Ativo',
  'inactive': 'Inativo',
  'name': 'Nome',
  'confirm_password': 'Confirmar Senha',
  'passwords_do_not_match': 'As senhas não coincidem',
  'field_required': 'Campo obrigatório',
  'invalid_email': 'E-mail inválido',
  'weak_password': 'Senha muito fraca (mínimo 6 caracteres)',
  'user_not_found': 'Usuário não encontrado',
  'wrong_password': 'Senha incorreta',
  'error': 'Erro',
  'success': 'Sucesso',
  'loading': 'Carregando...',
  'weekly_summary': 'Resumo Semanal',
  'last_measurements': 'Últimas Medições',
  'no_measurements': 'Nenhuma medição encontrada',
  'measurement_detail': 'Detalhe da Medição',
  'date': 'Data',
  'method': 'Método',
  'device': 'Dispositivo',
  'send_reset_email': 'Enviar e-mail de redefinição',
  'reset_email_sent': 'E-mail de redefinição enviado!',
};
